---
title: "Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(plotly)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
data("ny_noaa")
ny_noaa_scatter <- ny_noaa %>%
  filter(!is.na(prcp) & !is.na(snow) & !is.na(snwd) & !is.na(tmax)& !is.na(tmin)&(snow>0)&(prcp>0)&(snwd>0)) %>%
  sample_n(10000) # Optional sampling for dashboard speed

# Determine threshold for lower bound (e.g., 5th percentile)
lower_bound <- quantile(ny_noaa_scatter$snow, 0.01, na.rm = TRUE)
upper_bound <- quantile(ny_noaa_scatter$snow, 0.95, na.rm = TRUE)

# Filter data to exclude extremely low values
ny_noaa_filtered <- ny_noaa_scatter |>
  filter(snow > lower_bound)|>
  filter(snow < upper_bound)
```

```{r}
lower_bound
```

### Chart A

prcp: 降水量（单位：毫米的十分之一）
snow: 降雪量（毫米）
snwd: 积雪深度（毫米）
tmax: 最高气温（摄氏度的十分之一）
tmin: 最低气温（摄氏度的十分之一）

```{r}
prcp_range <- quantile(ny_noaa_filtered$prcp, probs = c(0.05, 0.95), na.rm = TRUE)

scatter_ggplot = 
  ny_noaa_filtered |>
  ggplot(aes(x = snow, y = snwd, color = prcp)) +
  geom_point(alpha = 0.10) +
  scale_color_viridis_c(option = "plasma") +  # Choose a vibrant color scale
  scale_color_gradient(low = "blue", high = "yellow", limits = prcp_range) +
  coord_cartesian()

ggplotly(scatter_ggplot)


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

ny_noaa %>%
  filter(!is.na(tmax)) %>%
  group_by(year = year(date), month = month(date)) %>%
  summarize(avg_tmax = mean(as.numeric(tmax), na.rm = TRUE), .groups = 'drop') %>%
  plot_ly(x = ~month, y = ~avg_tmax, type = 'scatter', mode = 'lines')


```

### Chart C

```{r}
plot_ly(data = ny_noaa, x = ~month(date), y = ~prcp, type = 'box')
```

